apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery
          image: ozselevente/picwatch:latest
          command: ["celery", "-A", "celery_worker", "worker", "--loglevel=info"]
          env:
            - name: BROKER_URL
              value: redis://redis:6379/0
            - name: DATABASE_URL
              value: postgresql://postgres:your_password@postgres-service:5432/postgres
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
