apiVersion: apps/v1
kind: Deployment
metadata:
  name: picwatch
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: picwatch
  template:
    metadata:
      labels:
        app: picwatch
    spec:
      containers:
        - name: picwatch
          image: ozselevente/picwatch:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: image-storage
              mountPath: /app/static/uploads
      volumes:
        - name: image-storage
          persistentVolumeClaim:
            claimName: image-storage-pvc
