apiVersion: apps/v1
kind: Deployment
metadata:
  name: picwatch
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: picwatch
  template:
    metadata:
      labels:
        app: picwatch
    spec:
      containers:
      - name: picwatch
        image: ozselevente/picwatch:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:your_password@postgres-service:5432/postgres
        volumeMounts:
        - name: image-storage
          mountPath: /app/static/uploads
      volumes:
      - name: image-storage
        persistentVolumeClaim:
          claimName: image-storage-pvc
