apiVersion: apps/v1
kind: Deployment
metadata:
  name: picwatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: picwatch
  template:
    metadata:
      labels:
        app: picwatch
    spec:
      containers:
        - name: picwatch
          image: ozselevente/picwatch:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://picwatch:picwatch@postgres-service:5432/picwatch_db
