apiVersion: apps/v1
kind: Deployment
metadata:
  name: picwatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: picwatch
  template:
    metadata:
      labels:
        app: picwatch
    spec:
      containers:
        - name: picwatch
          image: ozselevente/picwatch:{{ .Values.env.APP_VERSION }}
          ports:
            - containerPort: 8000
