apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Csak egy pod használhatja egyszerre az adatokat
  resources:
    requests:
      storage: 10Gi  # A kért tárolás mennyisége
