apiVersion: v1
kind: Pod
metadata:
  name: pg-resetwal
spec:
  containers:
    - name: pg-resetwal
      image: postgres:17
      command: ["sleep", "infinity"]
      securityContext:
        runAsUser: 999  # PostgreSQL default UID
        runAsGroup: 999
        allowPrivilegeEscalation: false
      volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-storage
      persistentVolumeClaim:
        claimName: postgres-pvc
  restartPolicy: Never
