apiVersion: apps/v1
kind: Deployment
metadata:
  name: picwatch-backend
  labels:
    app: picwatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: picwatch
  template:
    metadata:
      labels:
        app: picwatch
    spec:
      containers:
      - name: picwatch
        image: YOUR_DOCKERHUB_USERNAME/picwatch:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://user:password@postgres-service:5432/picwatch"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
