apiVersion: v1
kind: Pod
metadata:
  name: picwatch-pod
spec:
  containers:
    - name: picwatch-container
      image: ozselevente/picwatch:latest
      volumeMounts:
        - name: image-storage
          mountPath: /app/static/uploads  # A podon belüli mappa, ahol a képeket tárolod
  volumes:
    - name: image-storage
      persistentVolumeClaim:
        claimName: image-storage-pvc  # Hivatkozás a PVC-re
