name: CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.12

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pip/wheels
          key: ${{ runner.os }}-pip-${{ hashFiles('app/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake \
            libopenblas-dev liblapack-dev \
            libx11-dev libgtk-3-dev

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --prefer-binary --use-feature=fast-deps -r app/requirements.txt

#      - name: Lint with flake8
#        run: |
#          pip install flake8
#          flake8 app/

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_KEY }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/picwatch:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/picwatch:latest
