name: CI/CD


on:
  push:
    branches:
      - main

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.12

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 app/

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/picwatch:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/picwatch:latest
