name: CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install system build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake \
            libopenblas-dev liblapack-dev \
            libx11-dev libgtk-3-dev

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt

      # Linting lépés kiszedve
      # Cache kiszedve
      # --prefer-binary és --use-feature=fast-deps kiszedve

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_KEY }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/picwatch:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/picwatch:latest
