name: CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.12

      - name: Install system dependencies for face_recognition
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            libboost-all-dev \
            libopenblas-dev \
            liblapack-dev \
            libx11-dev \
            libgtk-3-dev \
            libatlas-base-dev \
            libdlib-dev \
            libopencv-dev \
            python3-dev

      - name: Install Python dependencies
        run: |
          pip install -r app/requirements.txt

#      - name: Lint with flake8
#        run: |
#          pip install flake8
#          flake8 app/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/picwatch:latest
